import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import SessionWrapper from "@/components/session-wrapper";
import { Toaster } from "@/components/ui/sonner";
import HeaderAdmin from "@/layouts/admin-layout/header-admin";
import SidebarAdmin from "@/layouts/admin-layout/sidebar-admin";

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: "Luxury Watches",
  description: "Generated by ThanhDoan",
};

type RootLayoutProps = Readonly<{
  children: ReactNode;
}>;

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={inter.className}>
          <div className="flex">
            <div className="w-auto">
              <SidebarAdmin />
            </div>
            <div className="flex-1 flex flex-col justify-between max-h-screen">
              <HeaderAdmin />
              <div className="flex-1 overflow-y-auto">{children}</div>
            </div>
          </div>
          <Toaster position="top-right" richColors theme="light" />
        </body>
      </html>
    </SessionWrapper>
  );
}
