import "../../global.css";
import HeaderAdmin from "@/layouts/admin-layout/header-admin";
import SidebarAdmin from "@/layouts/admin-layout/sidebar-admin";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <HeaderAdmin />
        <div className="flex gap-8 text-3xl">
          <SidebarAdmin />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
